# Gradienter
Fra `tensor.ipynb` i del 1 så vi på slutten at tensorer ikke er som helt vanlige flerdimensjonale Python lister, siden vi kan spesifisere hvilken GPU de skal ligge på.  
En annen viktig funksjonalitet som PyTorch tilbyr på denne datastrukturen er loggføring av hvilke operasjoner som utføres på tensorer, noe som er essensielt når nevrale nettverk trenes.

In [1]:
import torch

Loggføringen skjer bare på tensorer hvor flagget `requires_grad` settes, og på tensorer som deltar i en operasjon med en annen tensor som har det aktivert.  
Vi begynner med et enkelt eksempel for å vise hvordan denne loggen ser ut.

In [2]:
tensor = torch.rand(2, 2, requires_grad=True)
tensor

tensor([[0.4794, 0.5701],
        [0.9579, 0.1469]], requires_grad=True)

In [3]:
tensor = tensor + 2
tensor

tensor([[2.4794, 2.5701],
        [2.9579, 2.1470]], grad_fn=<AddBackward0>)

In [4]:
tensor = tensor * 10
tensor

tensor([[24.7945, 25.7011],
        [29.5788, 21.4695]], grad_fn=<MulBackward0>)

In [5]:
tensor = tensor / 10
tensor

tensor([[2.4794, 2.5701],
        [2.9579, 2.1470]], grad_fn=<DivBackward0>)

Etter hver operasjon får den nye tensoren en `grad_fn` tilknyttet seg som beskriver historikken. Loggen som konstrueres kalles for en _computational graph_, og vi kan sjekke den for å se at operasjonene er dokumentert. 

**Merk**: Dette gjør vi for moro skyld. Det er ikke noe man gjør i praksis. Hvordan PyTorch tar i bruk loggen for å trene nevrale nettverk skjer automatisk.

In [6]:
grad_fn = tensor.grad_fn
while len(grad_fn.next_functions) != 0:
    print(grad_fn)
    grad_fn = grad_fn.next_functions[0][0]
