In [1]:
!python -m pip install --user -q -r ../requirements.txt

In [2]:
import torch

# Indeksering

Når vi jobber med tensorer er det vanlig at vi ønsker å ekstrahere spesifikke data fra dem. Akkurat som Python-lister, kan vi hente ut bestemte elementer. Vi vil alltid få tilbake en tensor, og hvis resultatet inneholder bare ett tall, kan vi bruke `.item()` for å få en Python-datatype.

In [3]:
tensor = torch.Tensor([1, 2, 3])
print(tensor[0])
print(tensor[0].item())

tensor(1.)
1.0


Hvis tensoren har flere shape-dimensjoner, må vi indeksere oss gjennom disse.

In [4]:
tensor = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(tensor[1]) # Returns the second row
print(tensor[1][2]) # Returns the third element of the second row

tensor([4., 5., 6.])
tensor(6.)


Siste linje kan skrives mer kompakt:

In [5]:
tensor[1, 2]

tensor(6.)

## Indeksere med grenser
Noe som også er mulig i Python-lister, er at man kan indeksere med grenser.

In [6]:
tensor = torch.Tensor([1, 2, 3, 4, 5, 6])
tensor[1:4] # Returns a tensor with elements from index 1 to 3

tensor([2., 3., 4.])

In [7]:
tensor[:4] # Returns the first four elements

tensor([1., 2., 3., 4.])

In [8]:
tensor[3:] # Returns the last three elements

tensor([4., 5., 6.])

In [9]:
tensor[:-2] # Returns all elements except the last two

tensor([1., 2., 3., 4.])

In [10]:
tensor = torch.Tensor([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9], 
    [10, 11, 12]
])
tensor[1:3, 1:3] # Returns a tensor with rows 1 and 2, columns 1 and 2

tensor([[5., 6.],
        [8., 9.]])

En spesiell variant av indeksering må til hvis vi ønsker å hente ut bestemte elementer på tvers av shape-dimensjoner. Vi ser på et eksempel med en tensor som inneholder to matriser. 

In [11]:
tensor = torch.Tensor([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])
tensor[:, 1, 0] # Where : means all elements on that axis

tensor([ 4., 10.])

Ved å bruke `:` på den første shape-dimensjonen returneres hele tensoren, og de etterfølgende indekseringene utføres på alt innhold langs den. Med andre ord returneres det første elementet på andre rad i hver matrise.

Vi kan også indeksere med `:` på den andre shape-dimensjonen. 

In [12]:
tensor[1, :, 0] 

tensor([ 7., 10.])

Først indekseres den andre matrisen, før det første elementer fra hver rad hentes ut. 

Man kan også bruke `:` som siste indeks, men dette har ikke noe effekt siden operatoren returnerer alt innhold.

In [13]:
print(f"tensor[1, 1, :] returns {tensor[1, 1, :]}")
print(f"tensor[1, 1] returns {tensor[1, 1]}")
print(f"tensor[1, 1, :] is the same as tensor[1, 1]: {torch.allclose(tensor[1, 1, :], tensor[1, 1])}")


tensor[1, 1, :] returns tensor([10., 11., 12.])
tensor[1, 1] returns tensor([10., 11., 12.])
tensor[1, 1, :] is the same as tensor[1, 1]: True


## Indeksere med tensorer
Det er mulig å samle indekseringer i tensorer og indeksere med dem. Vi bruker da `LongTensor`. Si at man vil ha hjørnene i en $3 \times 3$ matrise.

In [14]:
tensor = torch.Tensor([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

row_indices = torch.LongTensor([0, 0, 2, 2])
col_indices = torch.LongTensor([0, 2, 0, 2])

for row, col in zip(row_indices, col_indices):
    print(f"Element at row {row} and column {col} is {tensor[row, col]}")

tensor[row_indices, col_indices]


Element at row 0 and column 0 is 1.0
Element at row 0 and column 2 is 3.0
Element at row 2 and column 0 is 7.0
Element at row 2 and column 2 is 9.0


tensor([1., 3., 7., 9.])

Man kan også indeksere det samme elementet flere ganger, men dette brukes derimot sjeldent.

In [15]:
indices = torch.LongTensor([1, 1, 1])
tensor[indices] # Returns the second row three times

tensor([[4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])

## Boolsk indeksering
Boolsk indeksering er svært nyttig, da det tillater spørringer mot elementer i tensorer. Si at vi vil ha alle elementer som er større enn 5.

In [16]:
indices = tensor > 5
indices


tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

Indekseringstensoren har samme shape som den originale tensoren, og består av binære verdier. Denne kan brukes direkte for å indeksere på tensoren.

In [17]:
tensor[indices] 

tensor([6., 7., 8., 9.])

Vi kan for eksempel hente ut alle rader der summen av elementene er større enn 10, men mindre enn 20

In [20]:
indices = (tensor.sum(dim=1) > 10) & (tensor.sum(dim=1) < 20)
indices


tensor([False,  True, False])

In [21]:
tensor[indices]

tensor([[4., 5., 6.]])