## Oppvarming til trening av nevrale nettverk TODO
Til nå ser PyTorch ut som et vanlig bibliotek for å manipulere matriser. Kanskje er du kjent med Numpy, og det som er presentert fram til nå tilbys også gjennom Numpy.

Det er to viktige funksjonaliteter `torch.Tensor` implementerer, som man ikke finner Numpy eller vanlige Python-lister:
1. Støtte for å flytte dataene mellom CPU og GPU (hvis installert på datamaskinen).
2. Loggføring av hvilke operasjoner som er gjort på tensoren (nyttiggjøres under trening)

Vi ser på det første punktet ved å lage en tensor og sjekke hvilken enhet den havner på.

In [1]:
import torch

Det andre punktet er loggføring av operasjoner på tensorer. Dette skjer bare på tensorer hvor flagget `requires_grad` er aktivert, og tensorer som deltar i en operasjon med en annen tensor som har det aktivert.

In [2]:
tensor = torch.rand(2, 2, requires_grad=True)
tensor

tensor([[0.4620, 0.3446],
        [0.7927, 0.9249]], requires_grad=True)

In [3]:
tensor = tensor + 2
tensor

tensor([[2.4620, 2.3446],
        [2.7927, 2.9249]], grad_fn=<AddBackward0>)

In [4]:
tensor = tensor * 10
tensor

tensor([[24.6197, 23.4461],
        [27.9272, 29.2492]], grad_fn=<MulBackward0>)

In [5]:
tensor = tensor / 10
tensor

tensor([[2.4620, 2.3446],
        [2.7927, 2.9249]], grad_fn=<DivBackward0>)

Vi kan sjekke loggen for å se at operasjonene er dokumentert. 

**Merk**: Dette gjør vi for moro skyld. Det er ikke noe man gjør i praksis. Hvordan PyTorch tar i bruk loggen for å trene nevrale nettverk skjer automatisk.

In [6]:
grad_fn = tensor.grad_fn
while len(grad_fn.next_functions) != 0:
    print(grad_fn)
    grad_fn = grad_fn.next_functions[0][0]
